### ISSUE TITLE
You will need to install Fontforge for Python 2 to use this script.

### ISSUE THREAD

**Issue by SeanSobey** [Rfvgyhn/docker-ligaturizer#1]
I am getting the following message using the [Hack](https://sourcefoundry.org/hack/) font.
```
Copyright (c) 2000-2019. See AUTHORS for Contributors.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
Version: 20190801
Based on sources from 10:15 UTC  2-Sep-2019-ML-D-GDK3.
Your version of iconv does not support the "Mac Roman" encoding.
If this causes problems, reconfigure --without-iconv.
Ligaturizer only supports Python 2.x due to a bug in Fontforge:
https://github.com/fontforge/fontforge/issues/3057
You will need to install Fontforge for Python 2 to use this script.
```

**Comment by rfvgyhn** [comment]
Looks like I preemptively upgraded to python 3 before [ligaturizer supported it](https://github.com/ToxicFrog/Ligaturizer/pull/68). Hopefully python 3 support is merged soon since font forge has [deprecated](https://github.com/fontforge/fontforge/releases/tag/20190801) use of python 2.

I've generated a new image on dockerhub that patches in support. Let me know if it still doesn't work for you.

**Comment by SeanSobey** [comment]
Thanks for the quick response. Yes the new image seems to have fixed that issue, but I am now getting another error:
```
Copyright (c) 2000-2019. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20190801
 Based on sources from 10:15 UTC  2-Sep-2019-ML-D-GDK3.
Your version of iconv does not support the "Mac Roman" encoding.
If this causes problems, reconfigure --without-iconv.The following table(s) in the font have been ignored by FontForge
    Ignoring 'DSIG' digital signature table
Ligaturizing font input (Hack) as 'Hack Ligaturized'
     ...using ligatures from fonts/fira/distr/otf/FiraCode-Regular.otf
Traceback (most recent call last): 
   File "ligaturize.py", line 336, in <module> 
   File "ligaturize.py", line 333, in main 
        ligaturize_font(**vars(parse_args())) 
   File "ligaturize.py", line 273, in ligaturize_font 
        creator.add_ligature(lig_spec['chars'], lig_spec['firacode_ligature_name']) 
   File "ligaturize.py", line 164, in add_ligature 
        self.font[ord(char)].glyphname = char
TypeError: ord() expected a character, but string of length 9 found     
```
This does seem to be an issue in Ligaturizer though, maybe I should report in an issue there?

**Comment by rfvgyhn** [comment]
It looks like it's a [known issue](https://github.com/ToxicFrog/Ligaturizer/issues/40#issuecomment-416404692) (it probably wouldn't be a bad idea to have it as a dedicated issue though).

Ligaturizer [releases](https://github.com/ToxicFrog/Ligaturizer/releases) come with a ligaturized hack font. Is that one different from the one you want to ligaturize?

**Comment by SeanSobey** [comment]
Thanks for looking in to it! I created an issue on the Ligaturizer repo.

I am looking at getting an updated version of Hack, the Ligaturizer releases have a slightly outdated version.

**Comment by ToxicFrog** [comment]
Py3 support for Ligaturizer was just merged, I'll try to cut a new release using it this weekend.
